swagger: "2.0"
info:
  version: "0.0.1"
  title: Mutants
host: localhost:3000
basePath: /
schemes:
  # remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mutants:
    x-swagger-router-controller: mutants
    get:
      description: Returns dna Analysis, when true is Mutant
      operationId: isMutant
      parameters:
        - name: Dna
          in: body
          description: The dna to analyze
          required: true
          type: array
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Response"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stats:
    x-swagger-router-controller: stats
    get:
      description: Returns mutant stats
      operationId: analisys
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StatsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Response:
    required:
      - message
    properties:
      message:
        type: string
  StatsResponse:
    required:
      - message
    properties:
      count_mutant_dna:
        type: integer
      count_human_dna:
        type: integer
      ratio:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
